/** @format */

export const Auditlist = [
  {
    Title: "Design system",
    Para: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
    Subtitle: "1.UI corrections",
    Linkicon: "linkimage",
    bio: "Ut enim ad minim veniam, quis nostrod exercitation ullamco laboris",
    Fileicon: "documentimage",
    Filebio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    Logo: "2.Logo rework",
    Linktitle: "Drive link",
    Link: "https://drive.google.com/drive/u/0/folders/1P4q7gb09-L6GgMe5RJlEKDOoGnA66PyH",
    Timing: "DEADLINE",
    Date: "06 JUNE,3.",
    Respond: "Respond back in",
    Clock: "clockimage",
    Two: "02",
    Three: "03",
    One: "01",
    Day: "days",
    Hour: "hours",
    Min: "mins",
    More: "See more",
    Less: "See less",
    Up: "uparrow",
    down: "downarrow",
  },
  {
    Title: "Design system",
    Para: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
    Subtitle: "1.UI corrections",
    Linkicon: "linkimage",
    bio: "Ut enim ad minim veniam, quis nostrod exercitation ullamco laboris",
    Fileicon: "documentimage",
    Filebio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    Logo: "2.Logo rework",
    Linktitle: "Drive link",
    Link: "https://drive.google.com/drive/u/0/folders/1P4q7gb09-L6GgMe5RJlEKDOoGnA66PyH",
    Timing: "DEADLINE",
    Date: "06 JUNE,2023.",
    Respond: "Respond back in",
    Clock: "clockimage",
    Two: "02",
    Three: "03",
    One: "01",
    Day: "days",
    Hour: "hours",
    Min: "mins",
    More: "See more",
    Less: "See less",
    Up: "uparrow",
    down: "downarrow",
  },
];
export const Archivetaskslist = [
  {
    Title: "Design system",
    Para: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
    More: "See more",
  },
  {
    Title: "Design system",
    Para: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
    More: "See more",
  },
];
